### PR TITLE
add: TelePay address

### PR DESCRIPTION
**Pull request by lugodev**
Hi, [TelePay](https://telepay.cash) is a payments gateway based on TON, the first of its kind in the ecosystem. It's aimed for creating merchant accounts, getting API keys and automating TON payments for businesses and individuals. It has a Web dashboard, a Telegram integration and more coming up.

Please, add our app to the address book, this is important to our users to identify the address in the scan. Thank you.

Here's more info:
https://t.me/TelePayCash/18

telepay-seo-cover

### CODE REVIEW

**Comment by lugodev** [comment]
More details in our launch post:

https://blog.telepay.cash/introducing-telepay

**Comment by catchainer** [comment]
Start using tonscan.org for first.

**Comment by lugodev** [comment]
@catchainer, we're using tonscan.org as our official explorer for TON transactions.

You can confirm it by creating an invoice in our service and completing a deposit.

image

**Comment by lugodev** [comment]
@catchainer, as [the debate](https://t.me/c/1692517303/82) keeps going on around this particular PR, I'd like to bring more to the discussion: [TelePay](https://telepay.cash) IS USING TonScan since DAY 1 as our official explorer. Your comment [here](https://github.com/catchain/tonscan/pull/10#issuecomment-1116359453) was rude and not well-informed.

You should first check the platform before missing information and making a decision based on a hurry.

It was TON RU who [asked](https://t.me/ruton/93) us to make PRs and contribute to TonScan's book address. Now your reaction is shameful.

Anyway, accepting the PR or not: We're developing our own explorer, to help our users identify our wallet address, something that the leader explorer (TonScan) should do. Luckily the blockchain is decentralized. This rejection just motivates us, even more, to keep contributing our part to the ecosystem.

**Comment by ingria** [comment]
@lugodev we've checked your project again and everything seems fine.

We have to carefully check all projects, because tonscan.org is used by a lot of people and we must be 200% sure that the addresses that we add are trustworthy in the long-term (addresses from `addrbook.json` are considered "official" of "verified"). Sometimes we make mistakes – sorry for that.

Anyway, I'm going to merge your PR, good luck with your explorer ❤️

**Comment by lugodev** [comment]
Thank you @ingria for providing further info about this and merging the PR.

I understand checking must be 200% accurate. That's why I thought it wasn't fair by @catchainer, who seems to have not checked. But that's ok.

Thanks.

**Pull request closed without merging**
