### PR TITLE
TON Bounty addresses updated

### PR DESCRIPTION
**Pull request by delovoyhomie**
TON Bounties [archive] - `EQDVCoEOZ5QTT-EbMtbTghftSDNn9ex7sJasUkWtCKkwTmgp`
TON Bounties - `EQA5xljPhtHC_YEyfSAzRjxugLGWUDPq-Yx3M15Ji32DeWHo`

### CODE REVIEW

**Comment by ingria** [comment]
Address book is now here: https://github.com/catchain/address-book

**Comment by delovoyhomie** [comment]
@ingria, thank you!
You've recently changed the rules, as last time I submitted a pull request to this repository (https://github.com/catchain/tonscan/pull/76).

**Comment by ingria** [comment]
Yes, that's a recent change. Unfortunately, I cannot transfer this PR to another repository, so you'd have to create a new one. Fortunately, that would be pretty easy.

**Comment by delovoyhomie** [comment]
https://github.com/catchain/address-book/pull/4

**Pull request closed without merging**
